# Generated by Django 5.1.7 on 2025-05-03 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0004_alter_adminuser_id_alter_customeruser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
