# Generated by Django 5.1.7 on 2025-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0005_products_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.ImageField(upload_to='product_media/'),
        ),
    ]
